//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int attendance_id { get; set; }
        public string diemdanh { get; set; }
        public Nullable<System.DateTime> ngaytruc { get; set; }
        public Nullable<int> catruc { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public string mssv { get; set; }
    
        public virtual HumanResource HumanResource { get; set; }
    }
}
