//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCenterEntities1 : DbContext
    {
        public ITCenterEntities1()
            : base("name=ITCenterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<HumanResource> HumanResources { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Navbar> Navbars { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual DbSet<SoftwareStorage> SoftwareStorages { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<SupportHistory> SupportHistories { get; set; }
        public virtual DbSet<Todo> Todoes { get; set; }
        public virtual DbSet<LandingContent> LandingContents { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
    }
}
