//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingContent
    {
        public int Id { get; set; }
        public string HeaderTitle { get; set; }
        public string HeaderSubtitle { get; set; }
        public string HeaderBackground { get; set; }
        public string BannerImage { get; set; }
        public string AboutTitle { get; set; }
        public string AboutContent { get; set; }
        public string ServicesTitle { get; set; }
        public string Service1Image { get; set; }
        public string Service1Title { get; set; }
        public string Service2Image { get; set; }
        public string Service2Title { get; set; }
        public string Service3Image { get; set; }
        public string Service3Title { get; set; }
        public string SpotlightTitle { get; set; }
        public string SpotlightSubtitle { get; set; }
        public string SpotlightImages { get; set; }
        public string FeatureImage { get; set; }
    }
}
