//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int scheduledetail_id { get; set; }
        public Nullable<int> catruc { get; set; }
        public Nullable<System.TimeSpan> giobatdau { get; set; }
        public Nullable<System.TimeSpan> gioketthuc { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
    }
}
