//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareStorage
    {
        public int software_id { get; set; }
        public string ten { get; set; }
        public string mota { get; set; }
        public string link { get; set; }
        public string mssv { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
    
        public virtual HumanResource HumanResource { get; set; }
    }
}
