//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportHistory
    {
        public int support_id { get; set; }
        public string hoten { get; set; }
        public string maKH { get; set; }
        public string tenmay { get; set; }
        public string loaihotro { get; set; }
        public Nullable<System.DateTime> ngaygui { get; set; }
        public string trangthai { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public string mssv { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
    
        public virtual HumanResource HumanResource { get; set; }
    }
}
